spring:
  application:
    name: Nosto Currency Converter

logging:
  level:
    root: info
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level)
            %logger.%M - %msg%n'
#currency:
#  api:
#    key:
#    url:

server:
  servlet:
    context-path: /nosto

currency:
  url: "http://api.exchangeratesapi.io/v1/latest?access_key=c1b8abf515ae305e6d8815ad70a108ac&format=1"
