spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Nosto Currency Converter
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: file:src/main/resources/templates/
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://ec2-54-91-188-254.compute-1.amazonaws.com:5432/d8q38b4o5dm4bo
    username: ehiizbugvqicdm
    password: c30bd2d206ddab40d821e9602661ab133dd1f684eda4b7190caf7037a639e136
logging:
  level:
    root: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

server:
  servlet:
    context-path: /nosto
  error:
    whitelabel:
      enabled: false
currency:
  url: "http://api.exchangeratesapi.io/v1/latest?access_key=c1b8abf515ae305e6d8815ad70a108ac&format=1"
